### ISSUE TITLE
Empty body when there is a file attachment 

### ISSUE THREAD

**Issue by narguelles** [Webklex/php-imap#92] opened 2021-01-22 10:54 UTC
**Describe the bug**
Returns an empty body when there is an attachment on the email. Already tried office 365 and gmail.

**Used config**

I already tried to remove the inline from the disposition array.
```php
    'options' => [
        'delimiter' => '/',
        'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
        'sequence' => \Webklex\PHPIMAP\IMAP::ST_MSGN,
        'fetch_body' => true,
        'fetch_flags' => true,
        'message_key' => 'list',
        'fetch_order' => 'asc',
        'dispositions' => ['attachment', 'inline'],
        'common_folders' => [
            "root" => "INBOX",
            "junk" => "INBOX/Junk",
            "draft" => "INBOX/Drafts",
            "sent" => "INBOX/Sent",
            "trash" => "INBOX/Trash",
        ],
        'open' => [
            // 'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ],
        'decoder' => [
            'message' => 'utf-8', // mimeheader
            'attachment' => 'utf-8' // mimeheader
        ]
    ],
```
**Code to Reproduce**
The troubling code section which produces the reported bug.
```php
$message->getHTMLBody(); or $message->getTextBody()
```

**Additional context**
I tried to look for all the attachment being fetched, there is always an undefined file which have a text/html mimetype (This only happens when there is an file attachment).

php: 7.2.5, using an 2.3 php-imap when the issue occured, but I already updated to both laravel-imap latest version.

**Comment by Webklex** [comment] 2021-01-22 19:09
Duplicate of https://github.com/Webklex/php-imap/issues/91

**Closed by Webklex** 2021-01-22 19:09 UTC
Labels: duplicate
