### ISSUE TITLE
V5.0 = Empty Response

### ISSUE THREAD

**Issue by FortuneV13** [Webklex/php-imap#362] opened 2023-01-19 14:28 UTC
Using the latest version I am now getting: 

```
Command failed to process:
Causes:
    - Empty response
```

When accessing: 
`$messages = $folder->messages()->all()->get();`

It was fine on version: 4.1

**Comment by Guite** [comment] 2023-01-23 12:51
Can confirm this issue. Downgrading to 4.x for the moment.

**Comment by freescout-helpdesk** [comment] 2023-01-26 11:25
Same here.

**Comment by zajinx** [comment] 2023-02-02 17:33
same error

**Comment by victorr99** [comment] 2023-02-10 09:47
I can also confirm this issue. I'm getting empty responses everywhere when using version v5.0.0.

**Comment by vagkaefer** [comment] 2023-02-10 20:30
Same error here, Downgrading to 4.x solved for now...

**Comment by FortuneV13** [comment] 2023-02-10 20:32
Is there any news on a fix?

**Comment by Webklex** [comment] 2023-02-13 17:54
Hi @FortuneV13 , @Guite , @freescout-helpdesk , @zajinx , @victorr99 , @vagkaefer ,
many thanks for reporting this issue. Unfortunately I can't make sense of it and I'm not able to reproduce this issue.

Please try to enable the debug mode inside your config - perhaps this could provide some insight.
Besides this, how does the stack-trace looks like? 

Best regards & thanks for reporting,

**Comment by vagkaefer** [comment] 2023-02-15 20:56
Hello @Webklex , sorry the delay, I was traveling... 

This is more info from the Debug

The script and config used:

```
$options = [
    'options' => [
        'soft_fail' => false,
        'rfc822' => true,
        'debug' => true,
    ],
];

$cm = new ClientManager($options);

$client = $cm->make([
    'host' => 'outlook.office365.com',
    'port' => 993,
    'encryption' => 'ssl',
    'validate_cert' => false,
    'username' => 'email@xxxxxx.com.br',
    'password' => $access_token,
    'protocol' => 'imap',
    'authentication' => "oauth",
]);

$client->connect();
$folder = $client->getFolder('INBOX');

$folder->query()->all()->get()->each(function ($message) use ($client) {
    var_dump($message);
});
```

The log:
```
$client->connect();
$folder = $client->getFolder('INBOX');

   << * OK The Microsoft Exchange IMAP4 service is ready. [xxxxxxxxxxxxxxxx]

   << TAG1 OK AUTHENTICATE completed.
   >> TAG2 LIST "" "*"

   << * LIST (\HasNoChildren) "/" Anota&AOcA9Q-es
   << * LIST (\HasNoChildren) "/" "Arquivo Morto"
   << * LIST (\Marked \HasNoChildren) "/" INBOX
   << * LIST (\HasNoChildren) "/" "Caixa de Sa&AO0-da"
   << * LIST (\HasChildren) "/" Calend&AOE-rio
   << * LIST (\HasNoChildren) "/" Calend&AOE-rio/Anivers&AOE-rios
   << * LIST (\HasNoChildren) "/" "Calend&AOE-rio/Feriados de Brasil"
   << * LIST (\HasChildren) "/" Contatos
   << * LIST (\HasNoChildren) "/" Historico
   << * LIST (\HasChildren) "/" "Hist&APM-rico de Conversa"
   << * LIST (\HasNoChildren \Sent) "/" "Itens Enviados"
   << * LIST (\HasNoChildren \Trash) "/" "Itens Exclu&AO0-dos"
   << * LIST (\HasNoChildren) "/" Journal
   << * LIST (\HasNoChildren \Junk) "/" "Lixo Eletr&APQ-nico"
   << * LIST (\HasNoChildren \Drafts) "/" Rascunhos
   << * LIST (\HasNoChildren) "/" Tarefas
   << TAG2 OK LIST completed.
   = Webklex\PHPIMAP\Folder {#5484
       +path: "INBOX",
       +name: "INBOX",
       +full_name: "INBOX",
       +delimiter: "/",
       +no_inferiors: false,
       +no_select: false,
       +marked: true,
       +has_children: false,
       +referral: false,
     }

> $folder->query()->all()->get()->each(function ($message) use ($client) {
                var_dump($message);
        });

   >> TAG3 SELECT "INBOX"

   << * 0 EXISTS
   << * 0 RECENT
   << * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
   << * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
   << * OK [UIDVALIDITY 14] UIDVALIDITY value
   << * OK [UIDNEXT 657] The next unique identifier value
   << TAG3 OK [READ-WRITE] SELECT completed.
   >> TAG4 UID SEARCH ALL

   << * SEARCH
   << TAG4 OK SEARCH completed.

      Webklex\PHPIMAP\Exceptions\ResponseException  Command failed to process:
            
         Causes:
         	- Empty response
         Commands send:
         	TAG4 UID SEARCH ALL\r\n
         Responses received:
         	* SEARCH\r\n
         	TAG4 OK SEARCH completed.\r\n
         Error occurred.

```

If I can help more or perform more tests, just ask

Tks

**Comment by freescout-helpdesk** [comment] 2023-02-22 07:42
We are doing:
```
$messages = $client->getFolder('INBOX')->query()->since(now()->subDays(3))->leaveUnread()->unseen()->limit(300, 1)->get();
```

Here is the result:
```
>> TAG4 SELECT "INBOX"

<< * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
<< * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
<< * 98 EXISTS
<< * 0 RECENT
<< * OK [UIDVALIDITY 1540371430] UIDs valid
<< * OK [UIDNEXT 1015] Predicted next UID
<< TAG4 OK [READ-WRITE] Select completed (0.003 + 0.000 + 0.002 secs).
>> TAG5 UID SEARCH SINCE "19-Feb-2023" UNSEEN

<< * SEARCH
<< TAG5 OK Search completed (0.001 + 0.000 secs).

Command failed to process:
Causes:
        - Empty response
Commands send:
        TAG5 UID SEARCH SINCE "19-Feb-2023" UNSEEN\r\n
Responses received:
        * SEARCH\r\n
        TAG5 OK Search completed (0.001 + 0.000 secs).\r\n
Error occurred
```

**Comment by craigpotter** [comment] 2023-02-27 16:35
I am getting this as well when running `$message->thread()` 

```
Command failed to process: Causes: - Empty response Commands send: TAG25 UID SEARCH HEADER In-Reply-To xxxxx@mail.gmail.com\r\n Responses received: * SEARCH\r\n TAG25 OK SEARCH completed.\r\n Error occurred
```

**Comment by vagkaefer** [comment] 2023-03-01 17:40
Working fine in version 5.0.1 committed yesterday

Thanks @Webklex

**Comment by Webklex** [comment] 2023-03-16 00:37
Thanks for all the feedback!

Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Please create a new issue if you can reproduce this issue with v5.1 - to hopefully separate the different causes should they still exist.

Best regards,

**Closed by Webklex** 2023-03-16 00:37 UTC
